### PR TITLE
Prepared basic functionality for the implementation of Dark- and Light-Theme

### PR DESCRIPTION
**Pull request by jon-pruessmeier**
Hey there,
I added an anonymous function as an onClick-function to the svg-logo of the moon so that it can toggle between the dark and light mode. I left there placeholders, so that further development can concentrate on the exact implementation in order to the CSS.

### CODE REVIEW

**Comment by BaseMax** [comment]
Hey jon (correct me if it's not correct)

Can you please attach screenshots from light and dark mode?

Thanks in advance
M.

**Comment by BaseMax** [comment]
Thank you for your contribution.

Sorry for the delay, Since was a sick week it was hard to checkout the PR.
I look at now and it good.
but we need to add more custom CSS for dark mode. (for example text need to WHITE at dark mode)

**Review by BaseMax — COMMENTED** [review]
Thank you

**Review by BaseMax — APPROVED** [review]
LGTM, Good as first version of dark mode

**Comment by jon-pruessmeier** [comment]
Thank you Max :)

**Pull request merged**
